In [27]:
import numpy as np

def dilate(image, structuring_element):
    output = np.zeros_like(image)
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            if image[i, j] == 1:
                for m in range(structuring_element.shape[0]):
                    for n in range(structuring_element.shape[1]):
                        ni, nj = i + m - structuring_element.shape[0] // 2, j + n - structuring_element.shape[1] // 2
                        if 0 <= ni < image.shape[0] and 0 <= nj < image.shape[1]:
                            output[ni, nj] = max(output[ni, nj], structuring_element[m, n])
    return output

def erode(image, structuring_element):
    output = np.ones_like(image)
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            if image[i, j] == 1:
                valid = True
                for m in range(structuring_element.shape[0]):
                    for n in range(structuring_element.shape[1]):
                        ni, nj = i + m - structuring_element.shape[0] // 2, j + n - structuring_element.shape[1] // 2
                        if 0 <= ni < image.shape[0] and 0 <= nj < image.shape[1]:
                            if structuring_element[m, n] == 1 and image[ni, nj] == 0:
                                valid = False
                if valid:
                    output[i, j] = 1
                else:
                    output[i, j] = 0
            else:
                output[i, j] = 0
    return output

def open_image(image, structuring_element):
    eroded = erode(image, structuring_element)
    opened = dilate(eroded, structuring_element)
    return opened

def close_image(image, structuring_element):
    dilated = dilate(image, structuring_element)
    closed = erode(dilated, structuring_element)
    return closed

# original
f = np.array([[0, 0, 0, 0, 0, 0, 0, 0],
              [0, 1, 1, 0, 0, 0, 1, 0],
              [0, 1, 1, 0, 0, 0, 1, 0],
              [0, 1, 1, 1, 0, 0, 1, 0],
              [0, 1, 1, 1, 0, 0, 1, 0],
              [0, 1, 1, 1, 1, 1, 1, 0],
              [0, 0, 0, 0, 1, 1, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 0]], dtype=np.uint8)

# structure element
S = np.array([[1, 1, 1]], dtype=np.uint8)

# erosion
dilated = dilate(f, S)

# dilate
eroded = erode(f, S)

# opening
opened = open_image(f, S)

# closing
closed = close_image(f, S)

print("dilated:\n", dilated)
print("eroded:\n", eroded)
print("opened:\n", opened)
print("closed:\n", closed)


dilated:
 [[0 0 0 0 0 0 0 0]
 [1 1 1 1 0 1 1 1]
 [1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]]
eroded:
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 1 1 1 1 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0]]
opened:
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0]
 [0 1 1 1 0 0 0 0]
 [0 1 1 1 1 1 1 0]
 [0 0 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0]]
closed:
 [[0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 1 1]
 [1 1 1 0 0 0 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 0]]


In [34]:
import numpy as np

# 팽창 연산 함수
def dilate(image, structuring_element):
    output = np.zeros_like(image)
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            if image[i, j] == 1:
                for m in range(structuring_element.shape[0]):
                    for n in range(structuring_element.shape[1]):
                        ni, nj = i + m - structuring_element.shape[0] // 2, j + n - structuring_element.shape[1] // 2
                        if 0 <= ni < image.shape[0] and 0 <= nj < image.shape[1]:
                            output[ni, nj] = max(output[ni, nj], structuring_element[m, n])
    return output

# 침식 연산 함수
def erode(image, structuring_element):
    output = np.ones_like(image)
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            if image[i, j] == 1:
                valid = True
                for m in range(structuring_element.shape[0]):
                    for n in range(structuring_element.shape[1]):
                        ni, nj = i + m - structuring_element.shape[0] // 2, j + n - structuring_element.shape[1] // 2
                        if 0 <= ni < image.shape[0] and 0 <= nj < image.shape[1]:
                            if structuring_element[m, n] == 1 and image[ni, nj] == 0:
                                valid = False
                if valid:
                    output[i, j] = 1
                else:
                    output[i, j] = 0
            else:
                output[i, j] = 0
    return output

# 원래 영상
f = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0, 1, 0, 0],
    [0, 1, 2, 1, 0, 1, 0, 1, 0],
    [1, 1, 3, 1, 1, 0, 2, 0, 0],
    [0, 1, 3, 1, 0, 0, 2, 0, 0],
    [0, 1, 2, 3, 4, 4, 3, 0, 0],
    [0, 0, 0, 1, 3, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0]
], dtype=np.uint8)

# 구조 요소
S = np.array([[0, 0, 0]], dtype=np.uint8)

# 팽창 연산
dilated = dilate(f, S)

# 침식 연산
eroded = erode(f, S)

print("팽창 결과:\n", dilated)
print("침식 결과:\n", eroded)


팽창 결과:
 [[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
침식 결과:
 [[0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 1 0 0]
 [0 1 0 1 0 1 0 1 0]
 [1 1 0 1 1 0 0 0 0]
 [0 1 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
